name: Cypress Tests

on: push
   
jobs:
  cypress_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests (getting-started)
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          group: '1-getting-started'

      - name: Run Cypress tests (2-advanced-example)
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          group: '2-advanced-example'

      